// Shown when Supabase is not yet configured

export const DEMO_TESTIMONIALS = [
  {
    id: 'demo-1',
    name: 'Suresh Mehta',
    location: 'Borivali West, Mumbai',
    review: 'R.K. Electricals did our entire flat wiring. The work is super clean — not a single wire visible. Very professional team, showed up on time and finished ahead of schedule.',
    rating: 5,
    is_active: true,
  },
  {
    id: 'demo-2',
    name: 'Priya Nair',
    location: 'Kandivali, Mumbai',
    review: 'I called them for a faulty switchboard. They identified the problem in 10 minutes and fixed it safely. Honest about pricing — no hidden charges. Highly recommend!',
    rating: 5,
    is_active: true,
  },
  {
    id: 'demo-3',
    name: 'Arun Deshmukh',
    location: 'Malad West, Mumbai',
    review: 'Used their AMC service for our office. Monthly inspections keep everything running smoothly. No sudden electrical issues since we started. Worth every rupee.',
    rating: 5,
    is_active: true,
  },
  {
    id: 'demo-4',
    name: 'Kavita Shah',
    location: 'Dahisar, Mumbai',
    review: 'Our interior designer recommended R.K. Electricals for our new home. The cove lighting and chandelier installation is absolutely perfect. Very skilled workers.',
    rating: 5,
    is_active: true,
  },
  {
    id: 'demo-5',
    name: 'Rakesh Tiwari',
    location: 'Borivali East, Mumbai',
    review: 'Builder-level work done for our apartment complex — 30+ flats, all wired on time and passed inspection first attempt. Excellent coordination by Kirit Bhai.',
    rating: 5,
    is_active: true,
  },
]

export const DEMO_PROJECTS = [
  {
    id: 'demo-p1',
    title: 'Luxury Villa Circuitry — Borivali West',
    description: 'Bespoke concealed wiring and automated control systems for a 5000 sq ft luxury residence.',
    category: 'residential',
    image_url: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80',
    is_active: true,
  },
  {
    id: 'demo-p2',
    title: 'Designer Switch Integration',
    description: 'Installation of premium modular touch switches and smart dimming systems.',
    category: 'residential',
    image_url: 'https://images.unsplash.com/photo-1585314062340-f1a5a7c9328d?w=800&q=80',
    is_active: true,
  },
  {
    id: 'demo-p3',
    title: 'Corporate HQ Electrical Infrastructure',
    description: 'Full-scale power distribution, server room UPS setup, and architectural lighting for a major corporate office.',
    category: 'commercial',
    image_url: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&q=80',
    is_active: true,
  },
  {
    id: 'demo-p4',
    title: 'Industrial Control Panels',
    description: 'Custom-built power distribution boards and safety switchgear for a manufacturing unit.',
    category: 'commercial',
    image_url: 'https://images.unsplash.com/photo-1454165833267-033f2a5ef3df?w=800&q=80',
    is_active: true,
  },
  {
    id: 'demo-p5',
    title: 'Residential High-Rise Wiring',
    description: 'Comprehensive electrical contracting for a 20-story luxury residential tower.',
    category: 'builder',
    image_url: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=800&q=80',
    is_active: true,
  },
  {
    id: 'demo-p6',
    title: 'Bespoke Lighting Design Integration',
    description: 'Custom lighting layouts, designer light fixtures, and smart dimming automation.',
    category: 'designer',
    image_url: 'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=800&q=80',
    is_active: true,
  },
]
